package org.hibernate.cfg.reveng;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.InputStream;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

import org.hibernate.cfg.JDBCMetaDataConfiguration;
import org.hibernate.tool.hbm2x.POJOExporter;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

public class MetaTagTest {
	
	private static String REVENG_XML =
			"<!DOCTYPE hibernate-reverse-engineering                                            \n"+
			"          SYSTEM                                                                   \n"+
	        "          'http://hibernate.sourceforge.net/hibernate-reverse-engineering-3.0.dtd'>\n"+
			"<hibernate-reverse-engineering>                                                    \n"+
	        "   <table name='TEST'>                                                             \n"+
            "      <column name='ID' property='id'>                                             \n"+
            "          <meta attribute='use-in-equals'>true</meta>                              \n"+
            "      </column>                                                                    \n"+
	        "   </table>                                                                        \n"+
			"</hibernate-reverse-engineering>                                                     ";

	@Rule
	public TemporaryFolder tempFolder = new TemporaryFolder();
	
	private JDBCMetaDataConfiguration jmdc = null;
	
	@Before
	public void setUp() throws SQLException {
		createDatabase();
		createConfiguration();
	}
	
	@Test
	public void testMetaTag() throws Exception {
		File outputDir = tempFolder.newFolder();
		POJOExporter exporter = new POJOExporter(jmdc, outputDir);		
		exporter.start();
		
		File testFile = new File(outputDir, "org/reveng/Test.java");
		Assert.assertTrue(testFile.exists());
		
		String str = new String(Files.readAllBytes(testFile.toPath()));
		Assert.assertNotEquals(-1, str.indexOf("Test generated by hbm2java"));
		Assert.assertEquals(-1, str.indexOf("equals"));
	}
	
	private void createDatabase() throws SQLException {
		Connection connection = DriverManager.getConnection("jdbc:h2:mem:test");
		Statement statement = connection.createStatement();
		statement.execute("CREATE TABLE TEST (ID INT PRIMARY KEY, NAME VARCHAR(255))");
	}
	
	private void createConfiguration() {
		jmdc = new JDBCMetaDataConfiguration();
		jmdc.setProperty("hibernate.dialect", "org.hibernate.dialect.H2Dialect");
		jmdc.setProperty("hibernate.connection.driver_class", "org.h2.Driver");
		jmdc.setProperty("hibernate.connection.username", "");
		jmdc.setProperty("hibernate.connection.url", "jdbc:h2:mem:test");
		jmdc.getProperties().remove("hibernate.default_catalog");
		jmdc.getProperties().remove("hibernate.default_schema");
		
		DefaultReverseEngineeringStrategy configurableNamingStrategy = new DefaultReverseEngineeringStrategy();
		configurableNamingStrategy.setSettings(
				new ReverseEngineeringSettings(configurableNamingStrategy)
					.setDefaultPackageName("org.reveng")
					.setCreateCollectionForForeignKey(false));
		jmdc.setReverseEngineeringStrategy(configurableNamingStrategy);
		OverrideRepository overrideRepository = new OverrideRepository();
		InputStream inputStream = new ByteArrayInputStream(REVENG_XML.getBytes());
		overrideRepository.addInputStream(inputStream);
		jmdc.setReverseEngineeringStrategy(overrideRepository.getReverseEngineeringStrategy(configurableNamingStrategy));
		
		jmdc.readFromJDBC();
	}
	
}
